name: rb_time_zone
version: 0.0.1

description: A time zone web component service.

homepage: https://github.com/RBWebComponents/rb-time-zone-dart
documentation: https://github.com/RBWebComponents/rb-time-zone-dart

authors:
- Rafael Brandão <rafa.bra@gmail.com>

environment:
  sdk: '>=1.4.0 <2.0.0'

dependencies:
  core_elements: '>=0.1.0 <0.2.0'
  polymer: '>=0.12.0 <0.13.0'

transformers:
- polymer:
    entry_points:
      - example/demo.html
    lint: false